### ISSUE TITLE
Signing Kernel Modules

### ISSUE THREAD

**Issue by sallymanda** [Bai-Chiang/homelab_automation#1]
Hey there :-) Wow! Such an impressive script, I'm going to test it out this week when I install Arch on my new production machine.

Just wondering if I'll be able to sign kernel modules for secure boot with this arrangement? I unfortunately need v4l2loopback for streaming.

**Comment by Bai-Chiang** [comment]
I think it could. It doesn't seems extra steps are needed if using Dynamic Kernel Module.[1] `sbctl` comes with a pacman hook [2] to auto-resign UKI if kernel or initramfs updated.

Adding `v4l2loopback-dkms`, `linux-headers` to `OTHER_PKGS` variable in the script, it should be included when building UKI at [this](https://wiki.archlinux.org/title/User:Bai-Chiang/Installation_guide_(full_disk_encryption,secure_boot,unified_kernel_image,btrfs)#Unified_kernel_image) step. Signing UKI step [3] should be the same. 

So I think you don't need to change anything if DKMS and linux headers are added to `OTHER_PKGS`. 

If you don't include these and install them afterwards, I think it should also works. Because installing DKMS or linux header mkinitcpio will regenerate UKI [4], then the pacman hook [2] will sign the new UKI.

Well, I don't use DKMS. This is just based on my quick search. It may need some extra steps that I missed.


[1] https://wiki.archlinux.org/title/Unified_kernel_image
[2] https://github.com/Foxboron/sbctl/blob/master/contrib/pacman/ZZ-sbctl.hook
[3] https://wiki.archlinux.org/title/User:Bai-Chiang/Installation_guide_(full_disk_encryption,secure_boot,unified_kernel_image,btrfs)#Sign_unified_kernel_image
[4] https://wiki.archlinux.org/title/User:Bai-Chiang/Installation_guide_(full_disk_encryption,secure_boot,unified_kernel_image,btrfs)#Modify_.preset_file
